apiVersion: v1
kind: Service
metadata:
  name: my-service-be-app
  labels:
    app: my-service-be-app
    app.kubernetes.io/part-of: bookstore
  annotations:
    prometheus.io/port: "my-service-be-app"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: be-app
  ports:
    - protocol: TCP
      port: 5051
      name: my-service-be-app
      targetPort: 5000
  type: LoadBalancer
