apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
        - name: my-be-app-newversion
          image: be-app-newvirsion:1.0
          ports:
            - containerPort: 5000
